global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]
      
scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "node-exporter"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["node-exporter:9100"]
  
  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

